;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Wed Sep 14 2022
; Processor: AT89C51
; Compiler:  ASEM-51 (Proteus)
;====================================================================

$NOMOD51
$INCLUDE (8051.MCU)

;====================================================================
; DEFINITIONS
;====================================================================

;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      org   0000h

      jmp   Start
;====================================================================
; CODE SEGMENT
;====================================================================

      org   0100h      
      
;p1.0 Bagian Sensor IR Tengah
;p1.1 Kanan
;p1.2 Kiri
Start:	
      MOV P2, #00000000b
      MOV P1, #00000000b
Loop:	
	JB P1.0, MotionKiri
	JB P1.4, MotionKanan
	;Jika detect maka maju
    JB P1.1, MotionMaju
	JB P1.3, MotionMaju
	JNB P1.0, Loop
	JNB P1.4, Loop
    jmp Loop
      
MotionMaju:
      MOV P2, #00000101b
      JMP Loop

MotionKiri:
	MOV P2, #00000100b
	JMP Loop

MotionKanan:
	MOV P2, #00000001b
	JMP Loop

VerifyLogikaMaju:
		MOV P2, #01001000b

;====================================================================
      END
